# Generated by Django 6.0.4 on 2026-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subject', models.CharField(choices=[('Informatique', 'Informatique'), ('Mathématiques', 'Mathématiques'), ('Physique', 'Physique'), ('Algorithmique', 'Algorithmique'), ('Réseaux', 'Réseaux'), ('Bases de données', 'Bases de données'), ('Anglais', 'Anglais'), ('Français', 'Français'), ('Électronique', 'Électronique'), ('Gestion', 'Gestion')], max_length=100, verbose_name='Matière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('priority', models.CharField(choices=[('urgente', 'Urgente'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('à faire', 'À faire'), ('en cours', 'En cours'), ('terminée', 'Terminée')], default='à faire', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-created_at'],
            },
        ),
    ]
