# Generated by Django 6.0.4 on 2026-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='xp_awarded',
            field=models.IntegerField(default=0, verbose_name='XP accordés'),
        ),
    ]
