# Generated by Django 4.2.30 on 2026-05-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], default='moyenne', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('à faire', 'À faire'), ('en cours', 'En cours'), ('terminée', 'Terminée')], default='à faire', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Mathématiques', 'Mathématiques'), ('Physique', 'Physique'), ('Algorithmique', 'Algorithmique'), ('Réseaux', 'Réseaux'), ('Bases de données', 'Bases de données'), ('Anglais', 'Anglais'), ('Français', 'Français'), ('Électronique', 'Électronique'), ('Gestion', 'Gestion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='xp_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
